<?php

define($client_id,"803149563547.apps.googleusercontent.com");
define($client_secret,"8x2bPiYt5gpCeVAFEaOf8bq7");
define($redirect_uri,"https://localhost/oauth2callback");
define($scope,"sphinx");
define($state,"sphinx");
define($access_type,"sphinx");


 = "1111111111111.apps.googleusercontent.com"; //your client id
 = "XxxXXxxXXxXXxXxXXXxXXXX"; //your client secret 
 = "http://YOUR-SITE.com/YOUR-PATH/";
 = "https://GOOGLE-SCOPE-TO-ACCESS"; //google scope to access
 = "profile"; //optional
 = "offline"; //optional - allows for retrieval of refresh_token for offline access


?>